apiVersion: v1
kind: ConfigMap
metadata:
  name: pitstop-workshop-configmap
data:
  DB_USER: "pitstop-user"
  DB_PASSWORD: "pitstop-user"
  DB_NAME: "pitstop"
  DB_HOST: "pitstop-workshop-database-service"
  DB_PORT: "3308"  # Change this from 3306 to 3307
  SERVICE_NAME: "pitstop-workshop"
  PORT: "3003"
  MESSAGE_BUS: "pitstop-rabbitmq-service"
  MESSAGE_BUS_USERNAME: "pitstop"
  MESSAGE_BUS_PASSWORD: "pitstop"
  MESSAGE_BUS_TIMEOUT: "500"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-workshop-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-workshop
  template:
    metadata:
      labels:
        app: pitstop-workshop
    spec:
      containers:
        - name: pitstop-workshop
          image: simo3011w/pitstop-workshop-planning
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: pitstop-workshop-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-workshop-service
spec:
  ports:
    - port: 3003
  type: NodePort
  selector:
    app: pitstop-workshop
